package controler;

enum State {
	HOME_VISITOR, HOME_ORGANIZER, HOME_STABLE, HOME_REFEREE, HOME_PLAYER,
	CALENDAR_ORGANIZER, CALENDAR_PLAYER, CALENDAR_REFEREE, CALENDAR_STANDARD,
	RANKING,
	STABLE_LIST, STABLE_INFO, PLAYER_INFO,
	STABLE_MANAGEMENT, ADD_TEAM, ADD_PLAYER, MODIFY_TEAM, MODIFY_PLAYER,
	ERROR,
	LOGIN;
}
